# Configuration Settings for ZED-F9P device

debug: 1                 # Range 0-4 (0 means no debug statements will print)

# device: /dev/ttyACM1
frame_id: base

uart1:
  baudrate: 115200
  in: 35
  out: 3

# uart2:
#   baudrate: 115200
#   in: 3
#   out: 35

# usb:
#   baudrate: 115200
#   in: 3
#   out: 3

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true
