# Configuration Settings for ZED-F9P device

debug: 1                 # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM2
frame_id: gps1

uart1:
  baudrate: 115200
  in: 3
  out: 3

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true
